version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Docker/frontend/Dockerfile
    volumes:
    - ./frontend:/app
    - "/app/node_modules"
    ports:
    - 3000:3000
    tty: true
