version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    ports:
    - 80:80
    networks:
    - frontend

  frontend:
    build:
      context: .
      dockerfile: ./Docker/frontend/Dockerfile
    image: blog-template-frontend:prod
    expose:
    - "3000"
    networks:
    - frontend

networks:
  frontend:
    driver: bridge

volumes:
  node_modules_volume:
    name: node_modules_volume
    driver: local
