version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    tty: true
    networks:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: ./Docker/frontend/Dockerfile
    volumes:
    - ./frontend:/app
    - "/app/node_modules"
    expose:
    - "3000"
    tty: true
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
